#!/bin/sh /etc/rc.common
# THIS IS THE INIT SCRIPT FOR OPENWRT

START=99
STOP=99
 
start() {        
        echo start
        python /root/hass/main.py
}                 
 
stop() {          
        echo stop
        kill -SIGTERM $(cat /tmp/mpd.pid)
}
